version: '3.8'
services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: uber
      POSTGRES_PASSWORD: uberpass
      POSTGRES_DB: uberdb
    ports:
      - '5432:5432'
    volumes:
      - ./infra/postgres/data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./infra/redis/data:/data

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - '2181:2181'

  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  user-service:
    build: ./user-service
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_USER=uber
      - DB_PASS=uberpass
      - DB_NAME=uberdb
      - REDIS_HOST=redis
      - KAFKA_BROKER=kafka:9092
    ports:
      - '4001:4000'
    depends_on:
      - postgres
      - redis
      - kafka

  driver-service:
    build: ./driver-service
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_USER=uber
      - DB_PASS=uberpass
      - DB_NAME=uberdb
      - REDIS_HOST=redis
      - KAFKA_BROKER=kafka:9092
    ports:
      - '4002:4000'
    depends_on:
      - postgres
      - redis
      - kafka

  booking-service:
    build: ./booking-service
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_USER=uber
      - DB_PASS=uberpass
      - DB_NAME=uberdb
      - REDIS_HOST=redis
      - KAFKA_BROKER=kafka:9092
    ports:
      - '4003:4000'
    depends_on:
      - postgres
      - redis
      - kafka

  payment-service:
    build: ./payment-service
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_USER=uber
      - DB_PASS=uberpass
      - DB_NAME=uberdb
      - REDIS_HOST=redis
      - KAFKA_BROKER=kafka:9092
      - RAZORPAY_KEY_ID=your_razorpay_key_id
      - RAZORPAY_KEY_SECRET=your_razorpay_key_secret
    ports:
      - '4004:4000'
    depends_on:
      - postgres
      - redis
      - kafka

  notification-service:
    build: ./notification-service
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_USER=uber
      - DB_PASS=uberpass
      - DB_NAME=uberdb
      - REDIS_HOST=redis
      - KAFKA_BROKER=kafka:9092
    ports:
      - '4005:4000'
    depends_on:
      - postgres
      - redis
      - kafka

  api-gateway:
    build: ./api-gateway
    environment:
      - NODE_ENV=development
      - USER_SERVICE_URL=http://user-service:4000
      - DRIVER_SERVICE_URL=http://driver-service:4000
      - BOOKING_SERVICE_URL=http://booking-service:4000
      - PAYMENT_SERVICE_URL=http://payment-service:4000
      - NOTIFICATION_SERVICE_URL=http://notification-service:4000
    ports:
      - '8080:8080'
    depends_on:
      - user-service
      - driver-service
      - booking-service
      - payment-service
      - notification-service

  frontend:
    build: ./frontend
    environment:
      - NODE_ENV=development
      - REACT_APP_API_GATEWAY_URL=http://localhost:8080
    ports:
      - '3000:3000'
    depends_on:
      - api-gateway

  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - api-gateway 